[project]
name = "jaxarc-baselines"
authors = ["Aadam <aadimator@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[dependencies]
python = ">=3.10,<3.12"

[pypi-dependencies]
jaxarc_baselines = { path = ".", editable = true }
JaxARC = { path = "../JaxARC", editable = true }
# stoix = { path = "./stoix", editable = true }

[target.linux.pypi-dependencies]
jax = { version = ">=0.4.23", extras = ["cuda12"] }

[target.osx.pypi-dependencies]
jax = { version = ">=0.4.23", extras = ["cpu"] }

