[project]
name = "jaxarc-baselines"
authors = ["Aadam <aadimator@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[dependencies]
python = ">=3.10,<3.12"

[pypi-dependencies]
jaxarc_baselines = { path = ".", editable = true }
JaxARC = { path = "../JaxARC", editable = true }
stoix = { path = "./stoix", editable = true }

# Add a version constraint for protobuf to fix the TypeError from tensorboard_logger.
protobuf = "~=3.20.0"

[target.linux.pypi-dependencies]
jax = { version = ">=0.4.23", extras = ["cuda12"] }

[target.osx.pypi-dependencies]
jax = { version = ">=0.4.23", extras = ["cpu"] }


[activation.env]
JAX_PLATFORMS = "cuda,cpu"
CUDA_VISIBLE_DEVICES = "3"
# XLA_FLAGS = "--xla_gpu_autotune_level=0"
JAX_COMPILATION_CACHE_DIR="/tmp/jax_cache"
LD_LIBRARY_PATH = ""