# Taken from https://github.com/volotat/ARC-Game/blob/main/tasks/levels.json
# There's no criteria for these splits, so these are subjective. https://github.com/volotat/ARC-Game/issues/7
# These contain only the tasks from `train` split. For a mix of `train` and `eval` see easy.yaml

task_ids:
  - "6773b310" # "training/6773b310.json",
  - "46442a0e" # "training/46442a0e.json",
  - "aedd82e4" # "training/aedd82e4.json",
  - "28e73c20" # "training/28e73c20.json",
  - "694f12f3" # "training/694f12f3.json",
  - "d364b489" # "training/d364b489.json",
  - "1e0a9b12" # "training/1e0a9b12.json",
  - "9565186b" # "training/9565186b.json",
  - "29c11459" # "training/29c11459.json",
  - "4c4377d9" # "training/4c4377d9.json",
  - "67a3c6ac" # "training/67a3c6ac.json",
  - "272f95fa" # "training/272f95fa.json",
  - "3618c87e" # "training/3618c87e.json",
  - "bb43febb" # "training/bb43febb.json",
  - "0d3d703e" # "training/0d3d703e.json",
  - "74dd1130" # "training/74dd1130.json",
  - "67e8384a" # "training/67e8384a.json",
  - "5117e062" # "training/5117e062.json",
  - "6c434453" # "training/6c434453.json",
  - "a9f96cdd" # "training/a9f96cdd.json",
  - "a5f85a15" # "training/a5f85a15.json",
  - "2281f1f4" # "training/2281f1f4.json",
  - "e73095fd" # "training/e73095fd.json",
  - "67385a82" # "training/67385a82.json",
  - "4938f0c2" # "training/4938f0c2.json",
  - "97999447" # "training/97999447.json",
  - "6d75e8bb" # "training/6d75e8bb.json",
  - "b6afb2da" # "training/b6afb2da.json",
  - "dc1df850" # "training/dc1df850.json",
  - "780d0b14" # "training/780d0b14.json",
  - "32597951" # "training/32597951.json",
  - "99fa7670" # "training/99fa7670.json",
  - "91714a58" # "training/91714a58.json",
  - "c8f0f002" # "training/c8f0f002.json",
  - "ba26e723" # "training/ba26e723.json",
  - "b548a754" # "training/b548a754.json",
  - "9dfd6313" # "training/9dfd6313.json",
  - "88a62173" # "training/88a62173.json",
  - "b94a9452" # "training/b94a9452.json",
  - "6b9890af" # "training/6b9890af.json",
  - "4258a5f9" # "training/4258a5f9.json",
  - "f8ff0b80" # "training/f8ff0b80.json",
  - "7f4411dc" # "training/7f4411dc.json",
  - "ba97ae07" # "training/ba97ae07.json",
  - "60b61512" # "training/60b61512.json",
  - "e9afcf9a" # "training/e9afcf9a.json",
  - "bdad9b1f" # "training/bdad9b1f.json",
  - "6d0aefbc" # "training/6d0aefbc.json",
  - "1caeab9d" # "training/1caeab9d.json",
  - "56ff96f3" # "training/56ff96f3.json",
  - "63613498" # "training/63613498.json",
  - "a85d4709" # "training/a85d4709.json",
  - "8d510a79" # "training/8d510a79.json",
  - "ea786f4a" # "training/ea786f4a.json",
  - "25d8a9c8" # "training/25d8a9c8.json",
  - "22233c11" # "training/22233c11.json",
  - "6150a2bd" # "training/6150a2bd.json",
  - "b91ae062" # "training/b91ae062.json",
  - "e3497940" # "training/e3497940.json",
  - "a2fd1cf0" # "training/a2fd1cf0.json",
  - "7468f01a" # "training/7468f01a.json",
  - "beb8660c" # "training/beb8660c.json",
  - "a1570a43" # "training/a1570a43.json",
  - "913fb3ed" # "training/913fb3ed.json",
  - "f25ffba3" # "training/f25ffba3.json",
  - "8e5a5113" # "training/8e5a5113.json",
  - "a48eeaf7" # "training/a48eeaf7.json",
  - "aabf363d" # "training/aabf363d.json",
  - "ea32f347" # "training/ea32f347.json",
  - "d43fd935" # "training/d43fd935.json",
  - "0962bcdd" # "training/0962bcdd.json",
  - "d10ecb37" # "training/d10ecb37.json",
  - "f8a8fe49" # "training/f8a8fe49.json",
  - "c909285e" # "training/c909285e.json",
  - "f76d97a5" # "training/f76d97a5.json",
  - "49d1d64f" # "training/49d1d64f.json",
  - "3f7978a0" # "training/3f7978a0.json",
  - "eb5a1d5d" # "training/eb5a1d5d.json",
  - "ddf7fa4f" # "training/ddf7fa4f.json",
  - "8efcae92" # "training/8efcae92.json",
  - "a65b410d" # "training/a65b410d.json",
  - "d06dbe63" # "training/d06dbe63.json",
  - "e76a88a6" # "training/e76a88a6.json",
  - "e8593010" # "training/e8593010.json",
  - "952a094c" # "training/952a094c.json",
  - "c0f76784" # "training/c0f76784.json",
  - "855e0971" # "training/855e0971.json",
  - "db3e9e38" # "training/db3e9e38.json",
  - "5168d44c" # "training/5168d44c.json",
  - "7b6016b9" # "training/7b6016b9.json",
  - "ae4f1146" # "training/ae4f1146.json",
  - "e179c5f4" # "training/e179c5f4.json",
  - "a699fb00" # "training/a699fb00.json",
  - "b27ca6d3" # "training/b27ca6d3.json",
  - "28bf18c6" # "training/28bf18c6.json",
  - "810b9b61" # "training/810b9b61.json",
  - "f8c80d96" # "training/f8c80d96.json",
  - "54d82841" # "training/54d82841.json",
  - "9af7a82c" # "training/9af7a82c.json",
  - "a8c38be5" # "training/a8c38be5.json",
  - "e26a3af2" # "training/e26a3af2.json",
  - "d406998b" # "training/d406998b.json",
  - "fafffa47" # "training/fafffa47.json",
  - "0ca9ddb6" # "training/0ca9ddb6.json",
  - "ac0a08a4" # "training/ac0a08a4.json",
  - "4522001f" # "training/4522001f.json",
  - "8a004b2b" # "training/8a004b2b.json",
  - "760b3cac" # "training/760b3cac.json",
  - "b60334d2" # "training/b60334d2.json",
  - "a61ba2ce" # "training/a61ba2ce.json",
  - "b8cdaf2b" # "training/b8cdaf2b.json",
  - "90f3ed37" # "training/90f3ed37.json",
  - "496994bd" # "training/496994bd.json",
  - "7ddcd7ec" # "training/7ddcd7ec.json",
  - "6855a6e4" # "training/6855a6e4.json",
  - "a3df8b1e" # "training/a3df8b1e.json",
  - "af902bf9" # "training/af902bf9.json",
  - "98cf29f8" # "training/98cf29f8.json",
  - "7e0986d6" # "training/7e0986d6.json",
  - "6d58a25d" # "training/6d58a25d.json",
  - "e50d258f" # "training/e50d258f.json",
  - "8d5021e8" # "training/8d5021e8.json",
  - "e5062a87" # "training/e5062a87.json",
  - "ef135b50" # "training/ef135b50.json",
  - "8e1813be" # "training/8e1813be.json",
  - "623ea044" # "training/623ea044.json",
  - "11852cab" # "training/11852cab.json",
  - "48d8fb45" # "training/48d8fb45.json",
  - "22168020" # "training/22168020.json",
  - "7447852a" # "training/7447852a.json",
  - "7fe24cdd" # "training/7fe24cdd.json",
  - "0520fde7" # "training/0520fde7.json",
  - "a78176bb" # "training/a78176bb.json",
  - "928ad970" # "training/928ad970.json",
  - "d6ad076f" # "training/d6ad076f.json",
  - "d89b689b" # "training/d89b689b.json",
  - "05f2a901" # "training/05f2a901.json",
  - "f8b3ba0a" # "training/f8b3ba0a.json",
  - "e8dc4411" # "training/e8dc4411.json",
  - "3bdb4ada" # "training/3bdb4ada.json",
  - "c3f564a4" # "training/c3f564a4.json",
  - "1f85a75f" # "training/1f85a75f.json",
  - "1fad071e" # "training/1fad071e.json",
  - "77fdfe62" # "training/77fdfe62.json",
  - "ec883f72" # "training/ec883f72.json",
  - "aba27056" # "training/aba27056.json",
  - "681b3aeb" # "training/681b3aeb.json",
  - "1f876c06" # "training/1f876c06.json",
  - "4093f84a" # "training/4093f84a.json",
  - "6e02f1e3" # "training/6e02f1e3.json",
  - "3c9b0459" # "training/3c9b0459.json",
  - "41e4d17e" # "training/41e4d17e.json",
  - "6e19193c" # "training/6e19193c.json",
  - "1f642eb9" # "training/1f642eb9.json",
  - "d511f180" # "training/d511f180.json",
  - "e21d9049" # "training/e21d9049.json",
  - "bd4472b8" # "training/bd4472b8.json",
  - "f25fbde4" # "training/f25fbde4.json",
  - "d8c310e9" # "training/d8c310e9.json",
  - "8403a5d5" # "training/8403a5d5.json",
  - "c9f8e694" # "training/c9f8e694.json",
  - "025d127b" # "training/025d127b.json",
  - "f2829549" # "training/f2829549.json",
  - "2dd70a9a" # "training/2dd70a9a.json",
  - "ce4f8723" # "training/ce4f8723.json",
  - "508bd3b6" # "training/508bd3b6.json",
  - "4c5c2cf0" # "training/4c5c2cf0.json",
  - "d4f3cd78" # "training/d4f3cd78.json",
  - "56dc2b01" # "training/56dc2b01.json",
  - "5ad4f10b" # "training/5ad4f10b.json",
  - "3af2c5a8" # "training/3af2c5a8.json",
  - "4347f46a" # "training/4347f46a.json",
  - "941d9a10" # "training/941d9a10.json",
  - "963e52fc" # "training/963e52fc.json",
  - "94f9d214" # "training/94f9d214.json",
  - "a416b8f3" # "training/a416b8f3.json",
  - "25d487eb" # "training/25d487eb.json",
  - "543a7ed5" # "training/543a7ed5.json",
  - "2c608aff" # "training/2c608aff.json",
  - "62c24649" # "training/62c24649.json",
  - "91413438" # "training/91413438.json",
  - "bbc9ae5d" # "training/bbc9ae5d.json",
  - "2013d3e2" # "training/2013d3e2.json",
  - "228f6490" # "training/228f6490.json",
  - "50cb2852" # "training/50cb2852.json",
  - "5c0a986e" # "training/5c0a986e.json",
  - "5582e5ca" # "training/5582e5ca.json",
  - "6fa7a44f" # "training/6fa7a44f.json",
  - "017c7c7b" # "training/017c7c7b.json",
  - "36d67576" # "training/36d67576.json",
  - "1b60fb0c" # "training/1b60fb0c.json",
  - "39a8645d" # "training/39a8645d.json",
  - "3345333e" # "training/3345333e.json",
  - "3ac3eb23" # "training/3ac3eb23.json",
  - "3bd67248" # "training/3bd67248.json",
  - "2bcee788" # "training/2bcee788.json",
  - "d4a91cb9" # "training/d4a91cb9.json",
  - "23581191" # "training/23581191.json",
  - "00d62c1b" # "training/00d62c1b.json",
  - "c9e6f938" # "training/c9e6f938.json",
  - "29623171" # "training/29623171.json",
  - "2204b7a8" # "training/2204b7a8.json",
  - "08ed6ac7" # "training/08ed6ac7.json",
  - "1bfc4729" # "training/1bfc4729.json",
  - "178fcbfb" # "training/178fcbfb.json",
  - "22eb0ac0" # "training/22eb0ac0.json",
  - "67a423a3" # "training/67a423a3.json",
  - "95990924" # "training/95990924.json",
  - "3de23699" # "training/3de23699.json",
  - "6455b5f5" # "training/6455b5f5.json",