# Taken from https://github.com/volotat/ARC-Game/blob/main/tasks/levels.json
# There's no criteria for these splits, so these are subjective. https://github.com/volotat/ARC-Game/issues/7

task_ids:
  - "fc754716" # "evaluation/fc754716.json",
  - "759f3fd3" # "evaluation/759f3fd3.json",
  - "e7dd8335" # "evaluation/e7dd8335.json",
  - "e69241bd" # "evaluation/e69241bd.json",
  - "8fbca751" # "evaluation/8fbca751.json",
  - "c8b7cc0f" # "evaluation/c8b7cc0f.json",
  - "7c9b52a0" # "evaluation/7c9b52a0.json",
  - "c7d4e6ad" # "evaluation/c7d4e6ad.json",
  - "17cae0c1" # "evaluation/17cae0c1.json",
  - "310f3251" # "evaluation/310f3251.json",
  - "0a1d4ef5" # "evaluation/0a1d4ef5.json",
  - "992798f6" # "evaluation/992798f6.json",
  - "2072aba6" # "evaluation/2072aba6.json",
  - "be03b35f" # "evaluation/be03b35f.json",
  - "00576224" # "evaluation/00576224.json",
  - "a934301b" # "evaluation/a934301b.json",
  - "6df30ad6" # "evaluation/6df30ad6.json",
  - "137f0df0" # "evaluation/137f0df0.json",
  - "e57337a4" # "evaluation/e57337a4.json",
  - "ef26cbf6" # "evaluation/ef26cbf6.json",
  - "f5aa3634" # "evaluation/f5aa3634.json",
  - "9f27f097" # "evaluation/9f27f097.json",
  - "bf699163" # "evaluation/bf699163.json",
  - "d4b1c2b1" # "evaluation/d4b1c2b1.json",
  - "d4c90558" # "evaluation/d4c90558.json",
  - "21f83797" # "evaluation/21f83797.json",
  - "62b74c02" # "evaluation/62b74c02.json",
  - "770cc55f" # "evaluation/770cc55f.json",
  - "d37a1ef5" # "evaluation/d37a1ef5.json",
  - "1da012fc" # "evaluation/1da012fc.json",
  - "351d6448" # "evaluation/351d6448.json",
  - "7bb29440" # "evaluation/7bb29440.json",
  - "b7fb29bc" # "evaluation/b7fb29bc.json",
  - "32e9702f" # "evaluation/32e9702f.json",
  - "67c52801" # "evaluation/67c52801.json",
  - "516b51b7" # "evaluation/516b51b7.json",
  - "5207a7b5" # "evaluation/5207a7b5.json",
  - "e133d23d" # "evaluation/e133d23d.json",
  - "1990f7a8" # "evaluation/1990f7a8.json",
  - "94414823" # "evaluation/94414823.json",
  - "bb52a14b" # "evaluation/bb52a14b.json",
  - "712bf12e" # "evaluation/712bf12e.json",
  - "e1baa8a4" # "evaluation/e1baa8a4.json",
  - "2c0b0aff" # "evaluation/2c0b0aff.json",
  - "bf32578f" # "evaluation/bf32578f.json",
  - "11e1fe23" # "evaluation/11e1fe23.json",
  - "62ab2642" # "evaluation/62ab2642.json",
  - "9b365c51" # "evaluation/9b365c51.json",
  - "4f537728" # "evaluation/4f537728.json",
  - "4e469f39" # "evaluation/4e469f39.json",
  - "917bccba" # "evaluation/917bccba.json",
  - "55059096" # "evaluation/55059096.json",
  - "358ba94e" # "evaluation/358ba94e.json",
  - "ae58858e" # "evaluation/ae58858e.json",
  - "782b5218" # "evaluation/782b5218.json",
  - "e88171ec" # "evaluation/e88171ec.json",
  - "31adaf00" # "evaluation/31adaf00.json",
  - "a680ac02" # "evaluation/a680ac02.json",
  - "e7639916" # "evaluation/e7639916.json",
  - "3979b1a8" # "evaluation/3979b1a8.json",
  - "0b17323b" # "evaluation/0b17323b.json",
  - "69889d6e" # "evaluation/69889d6e.json",
  - "58743b76" # "evaluation/58743b76.json",
  - "f3cdc58f" # "evaluation/f3cdc58f.json",
  - "9772c176" # "evaluation/9772c176.json",
  - "642248e4" # "evaluation/642248e4.json",
  - "50aad11f" # "evaluation/50aad11f.json",
  - "67636eac" # "evaluation/67636eac.json",
  - "551d5bf1" # "evaluation/551d5bf1.json",
  - "332efdb3" # "evaluation/332efdb3.json",
  - "506d28a5" # "evaluation/506d28a5.json",
  - "cd3c21df" # "evaluation/cd3c21df.json",
  - "a406ac07" # "evaluation/a406ac07.json",
  - "93b4f4b3" # "evaluation/93b4f4b3.json",
  - "3194b014" # "evaluation/3194b014.json",
  - "705a3229" # "evaluation/705a3229.json",
  - "c35c1b4c" # "evaluation/c35c1b4c.json",
  - "575b1a71" # "evaluation/575b1a71.json",
  - "84f2aca1" # "evaluation/84f2aca1.json",
  - "0d87d2a6" # "evaluation/0d87d2a6.json",
  - "292dd178" # "evaluation/292dd178.json",
  - "60c09cac" # "evaluation/60c09cac.json",
  - "639f5a19" # "evaluation/639f5a19.json",
  - "aee291af" # "evaluation/aee291af.json",
  - "c658a4bd" # "evaluation/c658a4bd.json",
  - "0bb8deee" # "evaluation/0bb8deee.json",
  - "73182012" # "evaluation/73182012.json",
  - "e9c9d9a1" # "evaluation/e9c9d9a1.json",
  - "45737921" # "evaluation/45737921.json",
  - "e9ac8c9e" # "evaluation/e9ac8c9e.json",
  - "e5790162" # "evaluation/e5790162.json",
  - "e7a25a18" # "evaluation/e7a25a18.json",
  - "3ee1011a" # "evaluation/3ee1011a.json",
  - "bd14c3bf" # "evaluation/bd14c3bf.json"