# Taken from https://github.com/volotat/ARC-Game/blob/main/tasks/levels.json
# There's no criteria for these splits, so these are subjective. https://github.com/volotat/ARC-Game/issues/7

task_ids:
  - "6773b310" # "training/6773b310.json",
  - "46442a0e" # "training/46442a0e.json",
  - "aedd82e4" # "training/aedd82e4.json",
  - "28e73c20" # "training/28e73c20.json",
  - "694f12f3" # "training/694f12f3.json",
  - "d364b489" # "training/d364b489.json",
  - "fc754716" # "evaluation/fc754716.json",
  - "1e0a9b12" # "training/1e0a9b12.json",
  - "9565186b" # "training/9565186b.json",
  - "29c11459" # "training/29c11459.json",
  - "4c4377d9" # "training/4c4377d9.json",
  - "67a3c6ac" # "training/67a3c6ac.json",
  - "272f95fa" # "training/272f95fa.json",
  - "3618c87e" # "training/3618c87e.json",
  - "759f3fd3" # "evaluation/759f3fd3.json",
  - "bb43febb" # "training/bb43febb.json",
  - "e7dd8335" # "evaluation/e7dd8335.json",
  - "0d3d703e" # "training/0d3d703e.json",
  - "74dd1130" # "training/74dd1130.json",
  - "67e8384a" # "training/67e8384a.json",
  - "e69241bd" # "evaluation/e69241bd.json",
  - "5117e062" # "training/5117e062.json",
  - "6c434453" # "training/6c434453.json",
  - "a9f96cdd" # "training/a9f96cdd.json",
  - "a5f85a15" # "training/a5f85a15.json",
  - "2281f1f4" # "training/2281f1f4.json",
  - "e73095fd" # "training/e73095fd.json",
  - "67385a82" # "training/67385a82.json",
  - "4938f0c2" # "training/4938f0c2.json",
  - "97999447" # "training/97999447.json",
  - "6d75e8bb" # "training/6d75e8bb.json",
  - "b6afb2da" # "training/b6afb2da.json",
  - "dc1df850" # "training/dc1df850.json",
  - "8fbca751" # "evaluation/8fbca751.json",
  - "780d0b14" # "training/780d0b14.json",
  - "c8b7cc0f" # "evaluation/c8b7cc0f.json",
  - "32597951" # "training/32597951.json",
  - "99fa7670" # "training/99fa7670.json",
  - "91714a58" # "training/91714a58.json",
  - "c8f0f002" # "training/c8f0f002.json",
  - "ba26e723" # "training/ba26e723.json",
  - "b548a754" # "training/b548a754.json",
  - "9dfd6313" # "training/9dfd6313.json",
  - "88a62173" # "training/88a62173.json",
  - "b94a9452" # "training/b94a9452.json",
  - "6b9890af" # "training/6b9890af.json",
  - "4258a5f9" # "training/4258a5f9.json",
  - "7c9b52a0" # "evaluation/7c9b52a0.json",
  - "c7d4e6ad" # "evaluation/c7d4e6ad.json",
  - "f8ff0b80" # "training/f8ff0b80.json",
  - "7f4411dc" # "training/7f4411dc.json",
  - "ba97ae07" # "training/ba97ae07.json",
  - "60b61512" # "training/60b61512.json",
  - "e9afcf9a" # "training/e9afcf9a.json",
  - "bdad9b1f" # "training/bdad9b1f.json",
  - "6d0aefbc" # "training/6d0aefbc.json",
  - "1caeab9d" # "training/1caeab9d.json",
  - "56ff96f3" # "training/56ff96f3.json",
  - "63613498" # "training/63613498.json",
  - "a85d4709" # "training/a85d4709.json",
  - "17cae0c1" # "evaluation/17cae0c1.json",
  - "310f3251" # "evaluation/310f3251.json",
  - "0a1d4ef5" # "evaluation/0a1d4ef5.json",
  - "8d510a79" # "training/8d510a79.json",
  - "ea786f4a" # "training/ea786f4a.json",
  - "992798f6" # "evaluation/992798f6.json",
  - "25d8a9c8" # "training/25d8a9c8.json",
  - "22233c11" # "training/22233c11.json",
  - "6150a2bd" # "training/6150a2bd.json",
  - "2072aba6" # "evaluation/2072aba6.json",
  - "b91ae062" # "training/b91ae062.json",
  - "be03b35f" # "evaluation/be03b35f.json",
  - "00576224" # "evaluation/00576224.json",
  - "e3497940" # "training/e3497940.json",
  - "a2fd1cf0" # "training/a2fd1cf0.json",
  - "7468f01a" # "training/7468f01a.json",
  - "beb8660c" # "training/beb8660c.json",
  - "a1570a43" # "training/a1570a43.json",
  - "913fb3ed" # "training/913fb3ed.json",
  - "f25ffba3" # "training/f25ffba3.json",
  - "8e5a5113" # "training/8e5a5113.json",
  - "a934301b" # "evaluation/a934301b.json",
  - "a48eeaf7" # "training/a48eeaf7.json",
  - "6df30ad6" # "evaluation/6df30ad6.json",
  - "137f0df0" # "evaluation/137f0df0.json",
  - "aabf363d" # "training/aabf363d.json",
  - "e57337a4" # "evaluation/e57337a4.json",
  - "ef26cbf6" # "evaluation/ef26cbf6.json",
  - "f5aa3634" # "evaluation/f5aa3634.json",
  - "9f27f097" # "evaluation/9f27f097.json",
  - "bf699163" # "evaluation/bf699163.json",
  - "ea32f347" # "training/ea32f347.json",
  - "d4b1c2b1" # "evaluation/d4b1c2b1.json",
  - "d4c90558" # "evaluation/d4c90558.json",
  - "d43fd935" # "training/d43fd935.json",
  - "21f83797" # "evaluation/21f83797.json",
  - "62b74c02" # "evaluation/62b74c02.json",
  - "0962bcdd" # "training/0962bcdd.json",
  - "d10ecb37" # "training/d10ecb37.json",
  - "f8a8fe49" # "training/f8a8fe49.json",
  - "770cc55f" # "evaluation/770cc55f.json",
  - "c909285e" # "training/c909285e.json",
  - "f76d97a5" # "training/f76d97a5.json",
  - "d37a1ef5" # "evaluation/d37a1ef5.json",
  - "49d1d64f" # "training/49d1d64f.json",
  - "3f7978a0" # "training/3f7978a0.json",
  - "eb5a1d5d" # "training/eb5a1d5d.json",
  - "ddf7fa4f" # "training/ddf7fa4f.json",
  - "8efcae92" # "training/8efcae92.json",
  - "a65b410d" # "training/a65b410d.json",
  - "d06dbe63" # "training/d06dbe63.json",
  - "e76a88a6" # "training/e76a88a6.json",
  - "1da012fc" # "evaluation/1da012fc.json",
  - "e8593010" # "training/e8593010.json",
  - "952a094c" # "training/952a094c.json",
  - "c0f76784" # "training/c0f76784.json",
  - "855e0971" # "training/855e0971.json",
  - "351d6448" # "evaluation/351d6448.json",
  - "7bb29440" # "evaluation/7bb29440.json",
  - "b7fb29bc" # "evaluation/b7fb29bc.json",
  - "db3e9e38" # "training/db3e9e38.json",
  - "5168d44c" # "training/5168d44c.json",
  - "7b6016b9" # "training/7b6016b9.json",
  - "32e9702f" # "evaluation/32e9702f.json",
  - "67c52801" # "evaluation/67c52801.json",
  - "ae4f1146" # "training/ae4f1146.json",
  - "e179c5f4" # "training/e179c5f4.json",
  - "a699fb00" # "training/a699fb00.json",
  - "b27ca6d3" # "training/b27ca6d3.json",
  - "28bf18c6" # "training/28bf18c6.json",
  - "516b51b7" # "evaluation/516b51b7.json",
  - "810b9b61" # "training/810b9b61.json",
  - "5207a7b5" # "evaluation/5207a7b5.json",
  - "e133d23d" # "evaluation/e133d23d.json",
  - "f8c80d96" # "training/f8c80d96.json",
  - "54d82841" # "training/54d82841.json",
  - "1990f7a8" # "evaluation/1990f7a8.json",
  - "94414823" # "evaluation/94414823.json",
  - "9af7a82c" # "training/9af7a82c.json",
  - "bb52a14b" # "evaluation/bb52a14b.json",
  - "a8c38be5" # "training/a8c38be5.json",
  - "e26a3af2" # "training/e26a3af2.json",
  - "712bf12e" # "evaluation/712bf12e.json",
  - "d406998b" # "training/d406998b.json",
  - "e1baa8a4" # "evaluation/e1baa8a4.json",
  - "fafffa47" # "training/fafffa47.json",
  - "2c0b0aff" # "evaluation/2c0b0aff.json",
  - "0ca9ddb6" # "training/0ca9ddb6.json",
  - "bf32578f" # "evaluation/bf32578f.json",
  - "11e1fe23" # "evaluation/11e1fe23.json",
  - "ac0a08a4" # "training/ac0a08a4.json",
  - "62ab2642" # "evaluation/62ab2642.json",
  - "9b365c51" # "evaluation/9b365c51.json",
  - "4522001f" # "training/4522001f.json",
  - "8a004b2b" # "training/8a004b2b.json",
  - "760b3cac" # "training/760b3cac.json",
  - "4f537728" # "evaluation/4f537728.json",
  - "b60334d2" # "training/b60334d2.json",
  - "4e469f39" # "evaluation/4e469f39.json",
  - "917bccba" # "evaluation/917bccba.json",
  - "a61ba2ce" # "training/a61ba2ce.json",
  - "55059096" # "evaluation/55059096.json",
  - "b8cdaf2b" # "training/b8cdaf2b.json",
  - "90f3ed37" # "training/90f3ed37.json",
  - "496994bd" # "training/496994bd.json",
  - "7ddcd7ec" # "training/7ddcd7ec.json",
  - "6855a6e4" # "training/6855a6e4.json",
  - "a3df8b1e" # "training/a3df8b1e.json",
  - "358ba94e" # "evaluation/358ba94e.json",
  - "af902bf9" # "training/af902bf9.json",
  - "98cf29f8" # "training/98cf29f8.json",
  - "ae58858e" # "evaluation/ae58858e.json",
  - "782b5218" # "evaluation/782b5218.json",
  - "7e0986d6" # "training/7e0986d6.json",
  - "e88171ec" # "evaluation/e88171ec.json",
  - "31adaf00" # "evaluation/31adaf00.json",
  - "6d58a25d" # "training/6d58a25d.json",
  - "a680ac02" # "evaluation/a680ac02.json",
  - "e50d258f" # "training/e50d258f.json",
  - "8d5021e8" # "training/8d5021e8.json",
  - "e5062a87" # "training/e5062a87.json",
  - "ef135b50" # "training/ef135b50.json",
  - "e7639916" # "evaluation/e7639916.json",
  - "3979b1a8" # "evaluation/3979b1a8.json",
  - "0b17323b" # "evaluation/0b17323b.json",
  - "8e1813be" # "training/8e1813be.json",
  - "623ea044" # "training/623ea044.json",
  - "11852cab" # "training/11852cab.json",
  - "48d8fb45" # "training/48d8fb45.json",
  - "22168020" # "training/22168020.json",
  - "7447852a" # "training/7447852a.json",
  - "69889d6e" # "evaluation/69889d6e.json",
  - "7fe24cdd" # "training/7fe24cdd.json",
  - "0520fde7" # "training/0520fde7.json",
  - "a78176bb" # "training/a78176bb.json",
  - "928ad970" # "training/928ad970.json",
  - "d6ad076f" # "training/d6ad076f.json",
  - "58743b76" # "evaluation/58743b76.json",
  - "d89b689b" # "training/d89b689b.json",
  - "f3cdc58f" # "evaluation/f3cdc58f.json",
  - "05f2a901" # "training/05f2a901.json",
  - "9772c176" # "evaluation/9772c176.json",
  - "f8b3ba0a" # "training/f8b3ba0a.json",
  - "e8dc4411" # "training/e8dc4411.json",
  - "642248e4" # "evaluation/642248e4.json",
  - "50aad11f" # "evaluation/50aad11f.json",
  - "3bdb4ada" # "training/3bdb4ada.json",
  - "67636eac" # "evaluation/67636eac.json",
  - "551d5bf1" # "evaluation/551d5bf1.json",
  - "332efdb3" # "evaluation/332efdb3.json",
  - "c3f564a4" # "training/c3f564a4.json",
  - "1f85a75f" # "training/1f85a75f.json",
  - "1fad071e" # "training/1fad071e.json",
  - "506d28a5" # "evaluation/506d28a5.json",
  - "77fdfe62" # "training/77fdfe62.json",
  - "ec883f72" # "training/ec883f72.json",
  - "aba27056" # "training/aba27056.json",
  - "681b3aeb" # "training/681b3aeb.json",
  - "cd3c21df" # "evaluation/cd3c21df.json",
  - "1f876c06" # "training/1f876c06.json",
  - "4093f84a" # "training/4093f84a.json",
  - "a406ac07" # "evaluation/a406ac07.json",
  - "6e02f1e3" # "training/6e02f1e3.json",
  - "3c9b0459" # "training/3c9b0459.json",
  - "41e4d17e" # "training/41e4d17e.json",
  - "93b4f4b3" # "evaluation/93b4f4b3.json",
  - "3194b014" # "evaluation/3194b014.json",
  - "6e19193c" # "training/6e19193c.json",
  - "1f642eb9" # "training/1f642eb9.json",
  - "d511f180" # "training/d511f180.json",
  - "e21d9049" # "training/e21d9049.json",
  - "705a3229" # "evaluation/705a3229.json",
  - "c35c1b4c" # "evaluation/c35c1b4c.json",
  - "bd4472b8" # "training/bd4472b8.json",
  - "f25fbde4" # "training/f25fbde4.json",
  - "d8c310e9" # "training/d8c310e9.json",
  - "8403a5d5" # "training/8403a5d5.json",
  - "c9f8e694" # "training/c9f8e694.json",
  - "575b1a71" # "evaluation/575b1a71.json",
  - "025d127b" # "training/025d127b.json",
  - "84f2aca1" # "evaluation/84f2aca1.json",
  - "0d87d2a6" # "evaluation/0d87d2a6.json",
  - "292dd178" # "evaluation/292dd178.json",
  - "60c09cac" # "evaluation/60c09cac.json",
  - "639f5a19" # "evaluation/639f5a19.json",
  - "aee291af" # "evaluation/aee291af.json",
  - "f2829549" # "training/f2829549.json",
  - "2dd70a9a" # "training/2dd70a9a.json",
  - "ce4f8723" # "training/ce4f8723.json",
  - "508bd3b6" # "training/508bd3b6.json",
  - "4c5c2cf0" # "training/4c5c2cf0.json",
  - "d4f3cd78" # "training/d4f3cd78.json",
  - "c658a4bd" # "evaluation/c658a4bd.json",
  - "56dc2b01" # "training/56dc2b01.json",
  - "5ad4f10b" # "training/5ad4f10b.json",
  - "3af2c5a8" # "training/3af2c5a8.json",
  - "4347f46a" # "training/4347f46a.json",
  - "941d9a10" # "training/941d9a10.json",
  - "0bb8deee" # "evaluation/0bb8deee.json",
  - "963e52fc" # "training/963e52fc.json",
  - "94f9d214" # "training/94f9d214.json",
  - "a416b8f3" # "training/a416b8f3.json",
  - "25d487eb" # "training/25d487eb.json",
  - "543a7ed5" # "training/543a7ed5.json",
  - "2c608aff" # "training/2c608aff.json",
  - "73182012" # "evaluation/73182012.json",
  - "62c24649" # "training/62c24649.json",
  - "91413438" # "training/91413438.json",
  - "bbc9ae5d" # "training/bbc9ae5d.json",
  - "2013d3e2" # "training/2013d3e2.json",
  - "228f6490" # "training/228f6490.json",
  - "50cb2852" # "training/50cb2852.json",
  - "5c0a986e" # "training/5c0a986e.json",
  - "5582e5ca" # "training/5582e5ca.json",
  - "6fa7a44f" # "training/6fa7a44f.json",
  - "017c7c7b" # "training/017c7c7b.json",
  - "e9c9d9a1" # "evaluation/e9c9d9a1.json",
  - "36d67576" # "training/36d67576.json",
  - "1b60fb0c" # "training/1b60fb0c.json",
  - "39a8645d" # "training/39a8645d.json",
  - "3345333e" # "training/3345333e.json",
  - "3ac3eb23" # "training/3ac3eb23.json",
  - "3bd67248" # "training/3bd67248.json",
  - "2bcee788" # "training/2bcee788.json",
  - "45737921" # "evaluation/45737921.json",
  - "d4a91cb9" # "training/d4a91cb9.json",
  - "23581191" # "training/23581191.json",
  - "00d62c1b" # "training/00d62c1b.json",
  - "c9e6f938" # "training/c9e6f938.json",
  - "29623171" # "training/29623171.json",
  - "2204b7a8" # "training/2204b7a8.json",
  - "e9ac8c9e" # "evaluation/e9ac8c9e.json",
  - "08ed6ac7" # "training/08ed6ac7.json",
  - "1bfc4729" # "training/1bfc4729.json",
  - "178fcbfb" # "training/178fcbfb.json",
  - "e5790162" # "evaluation/e5790162.json",
  - "22eb0ac0" # "training/22eb0ac0.json",
  - "67a423a3" # "training/67a423a3.json",
  - "95990924" # "training/95990924.json",
  - "3de23699" # "training/3de23699.json",
  - "6455b5f5" # "training/6455b5f5.json",
  - "e7a25a18" # "evaluation/e7a25a18.json",
  - "3ee1011a" # "evaluation/3ee1011a.json",
  - "bd14c3bf" # "evaluation/bd14c3bf.json"