# Taken from https://github.com/volotat/ARC-Game/blob/main/tasks/levels.json
# There's no criteria for these splits, so these are subjective. https://github.com/volotat/ARC-Game/issues/7


task_ids:
  - "f5c89df1" # "evaluation/f5c89df1.json",
  - "a096bf4d" # "evaluation/a096bf4d.json",
  - "505fff84" # "evaluation/505fff84.json",
  - "73c3b0d8" # "evaluation/73c3b0d8.json",
  - "2037f2c7" # "evaluation/2037f2c7.json",
  - "ac605cbb" # "evaluation/ac605cbb.json",
  - "c92b942c" # "evaluation/c92b942c.json",
  - "1acc24af" # "evaluation/1acc24af.json",
  - "ea9794b1" # "evaluation/ea9794b1.json",
  - "2685904e" # "evaluation/2685904e.json",
  - "3490cc26" # "evaluation/3490cc26.json",
  - "281123b4" # "evaluation/281123b4.json",
  - "14754a24" # "evaluation/14754a24.json",
  - "817e6c09" # "evaluation/817e6c09.json",
  - "e78887d1" # "evaluation/e78887d1.json",
  - "dc2e9a9d" # "evaluation/dc2e9a9d.json",
  - "fea12743" # "evaluation/fea12743.json",
  - "12422b43" # "evaluation/12422b43.json",
  - "e7b06bea" # "evaluation/e7b06bea.json",
  - "dc2aa30b" # "evaluation/dc2aa30b.json",
  - "8597cfd7" # "evaluation/8597cfd7.json",
  - "136b0064" # "evaluation/136b0064.json",
  - "84db8fc4" # "evaluation/84db8fc4.json",
  - "1c0d0a4b" # "evaluation/1c0d0a4b.json",
  - "4cd1b7b2" # "evaluation/4cd1b7b2.json",
  - "4ff4c9da" # "evaluation/4ff4c9da.json",
  - "e99362f0" # "evaluation/e99362f0.json",
  - "456873bc" # "evaluation/456873bc.json",
  - "3d31c5b3" # "evaluation/3d31c5b3.json",
  - "e6de6e8f" # "evaluation/e6de6e8f.json",
  - "f8be4b64" # "evaluation/f8be4b64.json",
  - "b0722778" # "evaluation/b0722778.json",
  - "1c56ad9f" # "evaluation/1c56ad9f.json",
  - "7d419a02" # "evaluation/7d419a02.json",
  - "85fa5666" # "evaluation/85fa5666.json",
  - "8ba14f53" # "evaluation/8ba14f53.json",
  - "184a9768" # "evaluation/184a9768.json",
  - "0607ce86" # "evaluation/0607ce86.json",
  - "15113be4" # "evaluation/15113be4.json",
  - "f9a67cb5" # "evaluation/f9a67cb5.json",
  - "df8cc377" # "evaluation/df8cc377.json",
  - "ca8de6ea" # "evaluation/ca8de6ea.json",
  - "d94c3b52" # "evaluation/d94c3b52.json",
  - "79369cc6" # "evaluation/79369cc6.json",
  - "94133066" # "evaluation/94133066.json",
  - "a8610ef7" # "evaluation/a8610ef7.json",
  - "423a55dc" # "evaluation/423a55dc.json",