# Taken from https://github.com/volotat/ARC-Game/blob/main/tasks/levels.json
# There's no criteria for these splits, so these are subjective. https://github.com/volotat/ARC-Game/issues/7


task_ids:
  - "0e206a2e" # "training/0e206a2e.json",
  - "445eab21" # "training/445eab21.json",
  - "8f2ea7aa" # "training/8f2ea7aa.json",
  - "29700607" # "evaluation/29700607.json",
  - "321b1fc6" # "training/321b1fc6.json",
  - "29ec7d0e" # "training/29ec7d0e.json",
  - "4612dd53" # "training/4612dd53.json",
  - "2dc579da" # "training/2dc579da.json",
  - "a61f2674" # "training/a61f2674.json",
  - "42918530" # "evaluation/42918530.json",
  - "444801d8" # "training/444801d8.json",
  - "0dfd9992" # "training/0dfd9992.json",
  - "7df24a62" # "training/7df24a62.json",
  - "1c02dbbe" # "evaluation/1c02dbbe.json",
  - "f45f5ca7" # "evaluation/f45f5ca7.json",
  - "1c786137" # "training/1c786137.json",
  - "6f473927" # "evaluation/6f473927.json",
  - "e98196ab" # "training/e98196ab.json",
  - "68b67ca3" # "evaluation/68b67ca3.json",
  - "ff72ca3e" # "evaluation/ff72ca3e.json",
  - "692cd3b6" # "evaluation/692cd3b6.json",
  - "b7249182" # "training/b7249182.json",
  - "e40b9e2f" # "training/e40b9e2f.json",
  - "642d658d" # "evaluation/642d658d.json",
  - "fcc82909" # "training/fcc82909.json",
  - "d2acf2cb" # "evaluation/d2acf2cb.json",
  - "c62e2108" # "evaluation/c62e2108.json",
  - "a3325580" # "training/a3325580.json",
  - "67b4a34d" # "evaluation/67b4a34d.json",
  - "54d9e175" # "training/54d9e175.json",
  - "dc0a314f" # "training/dc0a314f.json",
  - "7c008303" # "training/7c008303.json",
  - "e509e548" # "training/e509e548.json",
  - "27f8ce4f" # "evaluation/27f8ce4f.json",
  - "bc1d5164" # "training/bc1d5164.json",
  - "d13f3404" # "training/d13f3404.json",
  - "e6721834" # "training/e6721834.json",
  - "009d5c81" # "evaluation/009d5c81.json",
  - "e74e1818" # "evaluation/e74e1818.json",
  - "d9f24cd1" # "training/d9f24cd1.json",
  - "fcb5c309" # "training/fcb5c309.json",
  - "e5c44e8f" # "evaluation/e5c44e8f.json",
  - "b230c067" # "training/b230c067.json",
  - "9c1e755f" # "evaluation/9c1e755f.json",
  - "10fcaaa3" # "training/10fcaaa3.json",
  - "2f0c5170" # "evaluation/2f0c5170.json",
  - "5bd6f4ac" # "training/5bd6f4ac.json",
  - "cf133acc" # "evaluation/cf133acc.json",
  - "f1cefba8" # "training/f1cefba8.json",
  - "253bf280" # "training/253bf280.json",
  - "d23f8c26" # "training/d23f8c26.json",
  - "e4075551" # "evaluation/e4075551.json",
  - "c8cbb738" # "training/c8cbb738.json",
  - "7ee1c6ea" # "evaluation/7ee1c6ea.json",
  - "cb227835" # "evaluation/cb227835.json",
  - "140c817e" # "evaluation/140c817e.json",
  - "03560426" # "evaluation/03560426.json",
  - "1e32b0e9" # "training/1e32b0e9.json",
  - "cbded52d" # "training/cbded52d.json",
  - "93b581b8" # "training/93b581b8.json",
  - "ce22a75a" # "training/ce22a75a.json",
  - "20818e16" # "evaluation/20818e16.json",
  - "4364c1c4" # "evaluation/4364c1c4.json",
  - "42a15761" # "evaluation/42a15761.json",
  - "97a05b5b" # "training/97a05b5b.json",
  - "cf98881b" # "training/cf98881b.json",
  - "e48d4e1a" # "training/e48d4e1a.json",
  - "48131b3c" # "evaluation/48131b3c.json",
  - "aa300dc3" # "evaluation/aa300dc3.json",
  - "20981f0e" # "evaluation/20981f0e.json",
  - "ac2e8ecf" # "evaluation/ac2e8ecf.json",
  - "7c8af763" # "evaluation/7c8af763.json",
  - "890034e9" # "training/890034e9.json",
  - "fafd9572" # "evaluation/fafd9572.json",
  - "81c0276b" # "evaluation/81c0276b.json",
  - "695367ec" # "evaluation/695367ec.json",
  - "66f2d22f" # "evaluation/66f2d22f.json",
  - "bf89d739" # "evaluation/bf89d739.json",
  - "9ecd008a" # "training/9ecd008a.json",
  - "f83cb3f6" # "evaluation/f83cb3f6.json",
  - "4acc7107" # "evaluation/4acc7107.json",
  - "b7cb93ac" # "evaluation/b7cb93ac.json",
  - "d56f2372" # "evaluation/d56f2372.json",
  - "73ccf9c2" # "evaluation/73ccf9c2.json",
  - "447fd412" # "training/447fd412.json",
  - "f4081712" # "evaluation/f4081712.json",
  - "b15fca0b" # "evaluation/b15fca0b.json",
  - "1f0c79e5" # "training/1f0c79e5.json",
  - "0c9aba6e" # "evaluation/0c9aba6e.json",
  - "12eac192" # "evaluation/12eac192.json",
  - "64a7c07e" # "evaluation/64a7c07e.json",
  - "9caba7c3" # "evaluation/9caba7c3.json",
  - "50a16a69" # "evaluation/50a16a69.json",
  - "50f325b5" # "evaluation/50f325b5.json",
  - "2a5f8217" # "evaluation/2a5f8217.json",
  - "d492a647" # "evaluation/d492a647.json",
  - "ce039d91" # "evaluation/ce039d91.json",
  - "d47aa2ff" # "evaluation/d47aa2ff.json",
  - "7d18a6fb" # "evaluation/7d18a6fb.json",
  - "ed74f2f2" # "evaluation/ed74f2f2.json",
  - "0a2355a6" # "evaluation/0a2355a6.json",
  - "8ee62060" # "evaluation/8ee62060.json",
  - "9a4bb226" # "evaluation/9a4bb226.json",
  - "845d6e51" # "evaluation/845d6e51.json",
  - "4b6b68e5" # "evaluation/4b6b68e5.json",
  - "aa18de87" # "evaluation/aa18de87.json",
  - "9c56f360" # "evaluation/9c56f360.json",
  - "c3e719e8" # "training/c3e719e8.json",
  - "72322fa7" # "training/72322fa7.json",
  - "99b1bc43" # "training/99b1bc43.json",
  - "bc4146bd" # "evaluation/bc4146bd.json",
  - "477d2879" # "evaluation/477d2879.json",
  - "ff805c23" # "training/ff805c23.json",
  - "17b80ad2" # "evaluation/17b80ad2.json",
  - "ecdecbb3" # "training/ecdecbb3.json",
  - "80af3007" # "training/80af3007.json",
  - "2c737e39" # "evaluation/2c737e39.json",
  - "b942fd60" # "evaluation/b942fd60.json",
  - "ac3e2b04" # "evaluation/ac3e2b04.json",
  - "5daaa586" # "training/5daaa586.json",
  - "6a1e5592" # "training/6a1e5592.json",
  - "868de0fa" # "training/868de0fa.json",
  - "7953d61e" # "evaluation/7953d61e.json",
  - "0e671a1a" # "evaluation/0e671a1a.json",
  - "94be5b80" # "evaluation/94be5b80.json",
  - "c6e1b8da" # "evaluation/c6e1b8da.json",
  - "ded97339" # "training/ded97339.json",
  - "e2092e0c" # "evaluation/e2092e0c.json",
  - "13713586" # "evaluation/13713586.json",
  - "42a50994" # "training/42a50994.json",
  - "9d9215db" # "training/9d9215db.json",
  - "c1990cce" # "evaluation/c1990cce.json",
  - "cfb2ce5a" # "evaluation/cfb2ce5a.json",
  - "b20f7c8b" # "evaluation/b20f7c8b.json",
  - "212895b5" # "evaluation/212895b5.json",
  - "ed98d772" # "evaluation/ed98d772.json",
  - "626c0bcc" # "evaluation/626c0bcc.json",
  - "896d5239" # "evaluation/896d5239.json",
  - "103eff5b" # "evaluation/103eff5b.json",
  - "3a301edc" # "evaluation/3a301edc.json",
  - "195ba7dc" # "evaluation/195ba7dc.json",
  - "c64f1187" # "evaluation/c64f1187.json",
  - "8731374e" # "training/8731374e.json",
  - "37d3e8b2" # "evaluation/37d3e8b2.json",
  - "2546ccf6" # "evaluation/2546ccf6.json",
  - "d017b73f" # "evaluation/d017b73f.json",
  - "5ffb2104" # "evaluation/5ffb2104.json",
  - "baf41dbf" # "evaluation/baf41dbf.json",
  - "0f63c0b9" # "evaluation/0f63c0b9.json",
  - "48f8583b" # "evaluation/48f8583b.json",
  - "696d4842" # "evaluation/696d4842.json",
  - "150deff5" # "training/150deff5.json",
  - "c48954c1" # "evaluation/c48954c1.json",
  - "54db823b" # "evaluation/54db823b.json",
  - "d687bc17" # "training/d687bc17.json",
  - "af24b4cc" # "evaluation/af24b4cc.json",
  - "6cf79266" # "training/6cf79266.json",
  - "9356391f" # "evaluation/9356391f.json",
  - "6ad5bdfd" # "evaluation/6ad5bdfd.json",
  - "963f59bc" # "evaluation/963f59bc.json",
  - "08573cc6" # "evaluation/08573cc6.json",
  - "d19f7514" # "evaluation/d19f7514.json",
  - "9bebae7a" # "evaluation/9bebae7a.json",
  - "8dae5dfc" # "evaluation/8dae5dfc.json",
  - "f0afb749" # "evaluation/f0afb749.json",
  - "85b81ff1" # "evaluation/85b81ff1.json",
  - "6430c8c4" # "training/6430c8c4.json",
  - "8e2edd66" # "evaluation/8e2edd66.json",
  - "1b2d62fb" # "training/1b2d62fb.json",
  - "00dbd492" # "evaluation/00dbd492.json",
  - "0692e18c" # "evaluation/0692e18c.json",
  - "045e512c" # "training/045e512c.json",
  - "c3202e5a" # "evaluation/c3202e5a.json",
  - "72207abc" # "evaluation/72207abc.json",
  - "72a961c9" # "evaluation/72a961c9.json",
  - "6e82a1ae" # "training/6e82a1ae.json",
  - "7e02026e" # "evaluation/7e02026e.json",
  - "97239e3d" # "evaluation/97239e3d.json",
  - "3eda0437" # "training/3eda0437.json",
  - "a5313dff" # "training/a5313dff.json",
  - "d90796e8" # "training/d90796e8.json",
  - "cce03e0d" # "training/cce03e0d.json",
  - "3391f8c0" # "evaluation/3391f8c0.json",
  - "18419cfa" # "evaluation/18419cfa.json",
  - "45bbe264" # "evaluation/45bbe264.json",
  - "7d1f7ee8" # "evaluation/7d1f7ee8.json",
  - "85c4e7cd" # "training/85c4e7cd.json",
  - "22a4bbc2" # "evaluation/22a4bbc2.json",
  - "60a26a3e" # "evaluation/60a26a3e.json",
  - "0c786b71" # "evaluation/0c786b71.json",
  - "6cdd2623" # "training/6cdd2623.json",
  - "6ecd11f4" # "training/6ecd11f4.json",
  - "27a77e38" # "evaluation/27a77e38.json",
  - "776ffc46" # "training/776ffc46.json",
  - "99306f82" # "evaluation/99306f82.json",
  - "5521c0d9" # "training/5521c0d9.json",
  - "34b99a2b" # "evaluation/34b99a2b.json",
  - "ae3edfdc" # "training/ae3edfdc.json",
  - "0becf7df" # "evaluation/0becf7df.json",
  - "31aa019c" # "training/31aa019c.json",
  - "e0fb7511" # "evaluation/e0fb7511.json",
  - "8cb8642d" # "evaluation/8cb8642d.json",
  - "5af49b42" # "evaluation/5af49b42.json",
  - "5783df64" # "evaluation/5783df64.json",
  - "8a371977" # "evaluation/8a371977.json",
  - "d282b262" # "evaluation/d282b262.json",
  - "ce602527" # "training/ce602527.json",
  - "4290ef0e" # "training/4290ef0e.json",
  - "604001fa" # "evaluation/604001fa.json",
  - "ce9e57f2" # "training/ce9e57f2.json",
  - "1e81d6f9" # "evaluation/1e81d6f9.json",
  - "9def23fe" # "evaluation/9def23fe.json",
  - "6aa20dc0" # "training/6aa20dc0.json",
  - "2697da3f" # "evaluation/2697da3f.json",
  - "2b01abd0" # "evaluation/2b01abd0.json",
  - "6a11f6da" # "evaluation/6a11f6da.json",
  - "a8d7556c" # "training/a8d7556c.json",
  - "a87f7484" # "training/a87f7484.json",
  - "673ef223" # "training/673ef223.json",
  - "88a10436" # "training/88a10436.json",
  - "59341089" # "evaluation/59341089.json",
  - "9ddd00f0" # "evaluation/9ddd00f0.json",
  - "f35d900a" # "training/f35d900a.json",
  - "f5b8619d" # "training/f5b8619d.json",
  - "47c1f68c" # "training/47c1f68c.json",
  - "234bbc79" # "training/234bbc79.json",
  - "2bee17df" # "training/2bee17df.json",
  - "0b148d64" # "training/0b148d64.json",
  - "834ec97d" # "training/834ec97d.json",
  - "b2862040" # "training/b2862040.json",
  - "88207623" # "evaluation/88207623.json",
  - "1a07d186" # "training/1a07d186.json",
  - "007bbfb7" # "training/007bbfb7.json",
  - "82819916" # "training/82819916.json",
  - "90347967" # "evaluation/90347967.json",
  - "b7999b51" # "evaluation/b7999b51.json",
  - "3befdf3e" # "training/3befdf3e.json",
  - "e9bb6954" # "evaluation/e9bb6954.json",
  - "ce8d95cc" # "evaluation/ce8d95cc.json",
  - "f15e1fac" # "training/f15e1fac.json",
  - "a68b268e" # "training/a68b268e.json",
  - "137eaa0f" # "training/137eaa0f.json",
  - "15663ba9" # "evaluation/15663ba9.json",
  - "0a938d79" # "training/0a938d79.json",
  - "05269061" # "training/05269061.json",
  - "e633a9e5" # "evaluation/e633a9e5.json",
  - "e66aafb8" # "evaluation/e66aafb8.json",
  - "40853293" # "training/40853293.json",
  - "414297c0" # "evaluation/414297c0.json",
  - "36fdfd69" # "training/36fdfd69.json",
  - "b9630600" # "evaluation/b9630600.json",
  - "55783887" # "evaluation/55783887.json",
  - "15696249" # "evaluation/15696249.json",
  - "e9b4f6fc" # "evaluation/e9b4f6fc.json",
  - "ecaa0ec1" # "evaluation/ecaa0ec1.json",
  - "f823c43c" # "evaluation/f823c43c.json",
  - "f0df5ff0" # "evaluation/f0df5ff0.json",
  - "f21745ec" # "evaluation/f21745ec.json",
  - "fb791726" # "evaluation/fb791726.json",
  - "662c240a" # "training/662c240a.json",
  - "b0f4d537" # "evaluation/b0f4d537.json",
  - "4e45f183" # "evaluation/4e45f183.json",
  - "c87289bb" # "evaluation/c87289bb.json"