# Taken from https://github.com/volotat/ARC-Game/blob/main/tasks/levels.json
# There's no criteria for these splits, so these are subjective. https://github.com/volotat/ARC-Game/issues/7


task_ids:
  - "29700607" # "evaluation/29700607.json",
  - "42918530" # "evaluation/42918530.json",
  - "1c02dbbe" # "evaluation/1c02dbbe.json",
  - "f45f5ca7" # "evaluation/f45f5ca7.json",
  - "6f473927" # "evaluation/6f473927.json",
  - "68b67ca3" # "evaluation/68b67ca3.json",
  - "ff72ca3e" # "evaluation/ff72ca3e.json",
  - "692cd3b6" # "evaluation/692cd3b6.json",
  - "642d658d" # "evaluation/642d658d.json",
  - "d2acf2cb" # "evaluation/d2acf2cb.json",
  - "c62e2108" # "evaluation/c62e2108.json",
  - "67b4a34d" # "evaluation/67b4a34d.json",
  - "27f8ce4f" # "evaluation/27f8ce4f.json",
  - "009d5c81" # "evaluation/009d5c81.json",
  - "e74e1818" # "evaluation/e74e1818.json",
  - "e5c44e8f" # "evaluation/e5c44e8f.json",
  - "9c1e755f" # "evaluation/9c1e755f.json",
  - "2f0c5170" # "evaluation/2f0c5170.json",
  - "cf133acc" # "evaluation/cf133acc.json",
  - "e4075551" # "evaluation/e4075551.json",
  - "7ee1c6ea" # "evaluation/7ee1c6ea.json",
  - "cb227835" # "evaluation/cb227835.json",
  - "140c817e" # "evaluation/140c817e.json",
  - "03560426" # "evaluation/03560426.json",
  - "20818e16" # "evaluation/20818e16.json",
  - "4364c1c4" # "evaluation/4364c1c4.json",
  - "42a15761" # "evaluation/42a15761.json",
  - "48131b3c" # "evaluation/48131b3c.json",
  - "aa300dc3" # "evaluation/aa300dc3.json",
  - "20981f0e" # "evaluation/20981f0e.json",
  - "ac2e8ecf" # "evaluation/ac2e8ecf.json",
  - "7c8af763" # "evaluation/7c8af763.json",
  - "fafd9572" # "evaluation/fafd9572.json",
  - "81c0276b" # "evaluation/81c0276b.json",
  - "695367ec" # "evaluation/695367ec.json",
  - "66f2d22f" # "evaluation/66f2d22f.json",
  - "bf89d739" # "evaluation/bf89d739.json",
  - "f83cb3f6" # "evaluation/f83cb3f6.json",
  - "4acc7107" # "evaluation/4acc7107.json",
  - "b7cb93ac" # "evaluation/b7cb93ac.json",
  - "d56f2372" # "evaluation/d56f2372.json",
  - "73ccf9c2" # "evaluation/73ccf9c2.json",
  - "f4081712" # "evaluation/f4081712.json",
  - "b15fca0b" # "evaluation/b15fca0b.json",
  - "0c9aba6e" # "evaluation/0c9aba6e.json",
  - "12eac192" # "evaluation/12eac192.json",
  - "64a7c07e" # "evaluation/64a7c07e.json",
  - "9caba7c3" # "evaluation/9caba7c3.json",
  - "50a16a69" # "evaluation/50a16a69.json",
  - "50f325b5" # "evaluation/50f325b5.json",
  - "2a5f8217" # "evaluation/2a5f8217.json",
  - "d492a647" # "evaluation/d492a647.json",
  - "ce039d91" # "evaluation/ce039d91.json",
  - "d47aa2ff" # "evaluation/d47aa2ff.json",
  - "7d18a6fb" # "evaluation/7d18a6fb.json",
  - "ed74f2f2" # "evaluation/ed74f2f2.json",
  - "0a2355a6" # "evaluation/0a2355a6.json",
  - "8ee62060" # "evaluation/8ee62060.json",
  - "9a4bb226" # "evaluation/9a4bb226.json",
  - "845d6e51" # "evaluation/845d6e51.json",
  - "4b6b68e5" # "evaluation/4b6b68e5.json",
  - "aa18de87" # "evaluation/aa18de87.json",
  - "9c56f360" # "evaluation/9c56f360.json",
  - "bc4146bd" # "evaluation/bc4146bd.json",
  - "477d2879" # "evaluation/477d2879.json",
  - "17b80ad2" # "evaluation/17b80ad2.json",
  - "2c737e39" # "evaluation/2c737e39.json",
  - "b942fd60" # "evaluation/b942fd60.json",
  - "ac3e2b04" # "evaluation/ac3e2b04.json",
  - "7953d61e" # "evaluation/7953d61e.json",
  - "0e671a1a" # "evaluation/0e671a1a.json",
  - "94be5b80" # "evaluation/94be5b80.json",
  - "c6e1b8da" # "evaluation/c6e1b8da.json",
  - "e2092e0c" # "evaluation/e2092e0c.json",
  - "13713586" # "evaluation/13713586.json",
  - "c1990cce" # "evaluation/c1990cce.json",
  - "cfb2ce5a" # "evaluation/cfb2ce5a.json",
  - "b20f7c8b" # "evaluation/b20f7c8b.json",
  - "212895b5" # "evaluation/212895b5.json",
  - "ed98d772" # "evaluation/ed98d772.json",
  - "626c0bcc" # "evaluation/626c0bcc.json",
  - "896d5239" # "evaluation/896d5239.json",
  - "103eff5b" # "evaluation/103eff5b.json",
  - "3a301edc" # "evaluation/3a301edc.json",
  - "195ba7dc" # "evaluation/195ba7dc.json",
  - "c64f1187" # "evaluation/c64f1187.json",
  - "37d3e8b2" # "evaluation/37d3e8b2.json",
  - "2546ccf6" # "evaluation/2546ccf6.json",
  - "d017b73f" # "evaluation/d017b73f.json",
  - "5ffb2104" # "evaluation/5ffb2104.json",
  - "baf41dbf" # "evaluation/baf41dbf.json",
  - "0f63c0b9" # "evaluation/0f63c0b9.json",
  - "48f8583b" # "evaluation/48f8583b.json",
  - "696d4842" # "evaluation/696d4842.json",
  - "c48954c1" # "evaluation/c48954c1.json",
  - "54db823b" # "evaluation/54db823b.json",
  - "af24b4cc" # "evaluation/af24b4cc.json",
  - "9356391f" # "evaluation/9356391f.json",
  - "6ad5bdfd" # "evaluation/6ad5bdfd.json",
  - "963f59bc" # "evaluation/963f59bc.json",
  - "08573cc6" # "evaluation/08573cc6.json",
  - "d19f7514" # "evaluation/d19f7514.json",
  - "9bebae7a" # "evaluation/9bebae7a.json",
  - "8dae5dfc" # "evaluation/8dae5dfc.json",
  - "f0afb749" # "evaluation/f0afb749.json",
  - "85b81ff1" # "evaluation/85b81ff1.json",
  - "8e2edd66" # "evaluation/8e2edd66.json",
  - "00dbd492" # "evaluation/00dbd492.json",
  - "0692e18c" # "evaluation/0692e18c.json",
  - "c3202e5a" # "evaluation/c3202e5a.json",
  - "72207abc" # "evaluation/72207abc.json",
  - "72a961c9" # "evaluation/72a961c9.json",
  - "7e02026e" # "evaluation/7e02026e.json",
  - "97239e3d" # "evaluation/97239e3d.json",
  - "3391f8c0" # "evaluation/3391f8c0.json",
  - "18419cfa" # "evaluation/18419cfa.json",
  - "45bbe264" # "evaluation/45bbe264.json",
  - "7d1f7ee8" # "evaluation/7d1f7ee8.json",
  - "22a4bbc2" # "evaluation/22a4bbc2.json",
  - "60a26a3e" # "evaluation/60a26a3e.json",
  - "0c786b71" # "evaluation/0c786b71.json",
  - "27a77e38" # "evaluation/27a77e38.json",
  - "99306f82" # "evaluation/99306f82.json",
  - "34b99a2b" # "evaluation/34b99a2b.json",
  - "0becf7df" # "evaluation/0becf7df.json",
  - "e0fb7511" # "evaluation/e0fb7511.json",
  - "8cb8642d" # "evaluation/8cb8642d.json",
  - "5af49b42" # "evaluation/5af49b42.json",
  - "5783df64" # "evaluation/5783df64.json",
  - "8a371977" # "evaluation/8a371977.json",
  - "d282b262" # "evaluation/d282b262.json",
  - "604001fa" # "evaluation/604001fa.json",
  - "1e81d6f9" # "evaluation/1e81d6f9.json",
  - "9def23fe" # "evaluation/9def23fe.json",
  - "2697da3f" # "evaluation/2697da3f.json",
  - "2b01abd0" # "evaluation/2b01abd0.json",
  - "6a11f6da" # "evaluation/6a11f6da.json",
  - "59341089" # "evaluation/59341089.json",
  - "9ddd00f0" # "evaluation/9ddd00f0.json",
  - "88207623" # "evaluation/88207623.json",
  - "90347967" # "evaluation/90347967.json",
  - "b7999b51" # "evaluation/b7999b51.json",
  - "e9bb6954" # "evaluation/e9bb6954.json",
  - "ce8d95cc" # "evaluation/ce8d95cc.json",
  - "15663ba9" # "evaluation/15663ba9.json",
  - "e633a9e5" # "evaluation/e633a9e5.json",
  - "e66aafb8" # "evaluation/e66aafb8.json",
  - "414297c0" # "evaluation/414297c0.json",
  - "b9630600" # "evaluation/b9630600.json",
  - "55783887" # "evaluation/55783887.json",
  - "15696249" # "evaluation/15696249.json",
  - "e9b4f6fc" # "evaluation/e9b4f6fc.json",
  - "ecaa0ec1" # "evaluation/ecaa0ec1.json",
  - "f823c43c" # "evaluation/f823c43c.json",
  - "f0df5ff0" # "evaluation/f0df5ff0.json",
  - "f21745ec" # "evaluation/f21745ec.json",
  - "fb791726" # "evaluation/fb791726.json",
  - "b0f4d537" # "evaluation/b0f4d537.json",
  - "4e45f183" # "evaluation/4e45f183.json",
  - "c87289bb" # "evaluation/c87289bb.json"