# Taken from https://github.com/volotat/ARC-Game/blob/main/tasks/levels.json
# There's no criteria for these splits, so these are subjective. https://github.com/volotat/ARC-Game/issues/7


task_ids:
  - "0e206a2e" # "training/0e206a2e.json",
  - "445eab21" # "training/445eab21.json",
  - "8f2ea7aa" # "training/8f2ea7aa.json",
  - "321b1fc6" # "training/321b1fc6.json",
  - "29ec7d0e" # "training/29ec7d0e.json",
  - "4612dd53" # "training/4612dd53.json",
  - "2dc579da" # "training/2dc579da.json",
  - "a61f2674" # "training/a61f2674.json",
  - "444801d8" # "training/444801d8.json",
  - "0dfd9992" # "training/0dfd9992.json",
  - "7df24a62" # "training/7df24a62.json",
  - "1c786137" # "training/1c786137.json",
  - "e98196ab" # "training/e98196ab.json",
  - "b7249182" # "training/b7249182.json",
  - "e40b9e2f" # "training/e40b9e2f.json",
  - "fcc82909" # "training/fcc82909.json",
  - "a3325580" # "training/a3325580.json",
  - "54d9e175" # "training/54d9e175.json",
  - "dc0a314f" # "training/dc0a314f.json",
  - "7c008303" # "training/7c008303.json",
  - "e509e548" # "training/e509e548.json",
  - "bc1d5164" # "training/bc1d5164.json",
  - "d13f3404" # "training/d13f3404.json",
  - "e6721834" # "training/e6721834.json",
  - "d9f24cd1" # "training/d9f24cd1.json",
  - "fcb5c309" # "training/fcb5c309.json",
  - "b230c067" # "training/b230c067.json",
  - "10fcaaa3" # "training/10fcaaa3.json",
  - "5bd6f4ac" # "training/5bd6f4ac.json",
  - "f1cefba8" # "training/f1cefba8.json",
  - "253bf280" # "training/253bf280.json",
  - "d23f8c26" # "training/d23f8c26.json",
  - "c8cbb738" # "training/c8cbb738.json",
  - "1e32b0e9" # "training/1e32b0e9.json",
  - "cbded52d" # "training/cbded52d.json",
  - "93b581b8" # "training/93b581b8.json",
  - "ce22a75a" # "training/ce22a75a.json",
  - "97a05b5b" # "training/97a05b5b.json",
  - "cf98881b" # "training/cf98881b.json",
  - "e48d4e1a" # "training/e48d4e1a.json",
  - "890034e9" # "training/890034e9.json",
  - "9ecd008a" # "training/9ecd008a.json",
  - "447fd412" # "training/447fd412.json",
  - "1f0c79e5" # "training/1f0c79e5.json",
  - "c3e719e8" # "training/c3e719e8.json",
  - "72322fa7" # "training/72322fa7.json",
  - "99b1bc43" # "training/99b1bc43.json",
  - "ff805c23" # "training/ff805c23.json",
  - "ecdecbb3" # "training/ecdecbb3.json",
  - "80af3007" # "training/80af3007.json",
  - "5daaa586" # "training/5daaa586.json",
  - "6a1e5592" # "training/6a1e5592.json",
  - "868de0fa" # "training/868de0fa.json",
  - "ded97339" # "training/ded97339.json",
  - "42a50994" # "training/42a50994.json",
  - "9d9215db" # "training/9d9215db.json",
  - "8731374e" # "training/8731374e.json",
  - "150deff5" # "training/150deff5.json",
  - "d687bc17" # "training/d687bc17.json",
  - "6cf79266" # "training/6cf79266.json",
  - "6430c8c4" # "training/6430c8c4.json",
  - "1b2d62fb" # "training/1b2d62fb.json",
  - "045e512c" # "training/045e512c.json",
  - "6e82a1ae" # "training/6e82a1ae.json",
  - "3eda0437" # "training/3eda0437.json",
  - "a5313dff" # "training/a5313dff.json",
  - "d90796e8" # "training/d90796e8.json",
  - "cce03e0d" # "training/cce03e0d.json",
  - "85c4e7cd" # "training/85c4e7cd.json",
  - "6cdd2623" # "training/6cdd2623.json",
  - "6ecd11f4" # "training/6ecd11f4.json",
  - "776ffc46" # "training/776ffc46.json",
  - "5521c0d9" # "training/5521c0d9.json",
  - "ae3edfdc" # "training/ae3edfdc.json",
  - "31aa019c" # "training/31aa019c.json",
  - "ce602527" # "training/ce602527.json",
  - "4290ef0e" # "training/4290ef0e.json",
  - "ce9e57f2" # "training/ce9e57f2.json",
  - "6aa20dc0" # "training/6aa20dc0.json",
  - "a8d7556c" # "training/a8d7556c.json",
  - "a87f7484" # "training/a87f7484.json",
  - "673ef223" # "training/673ef223.json",
  - "88a10436" # "training/88a10436.json",
  - "f35d900a" # "training/f35d900a.json",
  - "f5b8619d" # "training/f5b8619d.json",
  - "47c1f68c" # "training/47c1f68c.json",
  - "234bbc79" # "training/234bbc79.json",
  - "2bee17df" # "training/2bee17df.json",
  - "0b148d64" # "training/0b148d64.json",
  - "834ec97d" # "training/834ec97d.json",
  - "b2862040" # "training/b2862040.json",
  - "1a07d186" # "training/1a07d186.json",
  - "007bbfb7" # "training/007bbfb7.json",
  - "82819916" # "training/82819916.json",
  - "3befdf3e" # "training/3befdf3e.json",
  - "f15e1fac" # "training/f15e1fac.json",
  - "a68b268e" # "training/a68b268e.json",
  - "137eaa0f" # "training/137eaa0f.json",
  - "0a938d79" # "training/0a938d79.json",
  - "05269061" # "training/05269061.json",
  - "40853293" # "training/40853293.json",
  - "36fdfd69" # "training/36fdfd69.json",
  - "662c240a" # "training/662c240a.json",