# Taken from https://github.com/volotat/ARC-Game/blob/main/tasks/levels.json
# There's no criteria for these splits, so these are subjective. https://github.com/volotat/ARC-Game/issues/7


task_ids:
  - "4852f2fa" # "evaluation/4852f2fa.json",
  - "e21a174a" # "evaluation/e21a174a.json",
  - "ff28f65a" # "training/ff28f65a.json",
  - "d4469b4b" # "training/d4469b4b.json",
  - "dc433765" # "training/dc433765.json",
  - "da2b0fe3" # "evaluation/da2b0fe3.json",
  - "31d5ba1a" # "evaluation/31d5ba1a.json",
  - "dae9d2b5" # "training/dae9d2b5.json",
  - "c074846d" # "evaluation/c074846d.json",
  - "794b24be" # "training/794b24be.json",
  - "bbb1b8b6" # "evaluation/bbb1b8b6.json",
  - "12997ef3" # "evaluation/12997ef3.json",
  - "25ff71a9" # "training/25ff71a9.json",
  - "e345f17b" # "evaluation/e345f17b.json",
  - "d5c634a2" # "evaluation/d5c634a2.json",
  - "e9614598" # "training/e9614598.json",
  - "b1fc8b8e" # "evaluation/b1fc8b8e.json",
  - "4c177718" # "evaluation/4c177718.json",
  - "f3e62deb" # "evaluation/f3e62deb.json",
  - "3428a4f5" # "training/3428a4f5.json",
  - "239be575" # "training/239be575.json",
  - "bda2d7a6" # "training/bda2d7a6.json",
  - "5d2a5c43" # "evaluation/5d2a5c43.json",
  - "53b68214" # "training/53b68214.json",
  - "1d398264" # "evaluation/1d398264.json",
  - "3b4c2228" # "evaluation/3b4c2228.json",
  - "8b28cd80" # "evaluation/8b28cd80.json",
  - "9b4c17c4" # "evaluation/9b4c17c4.json",
  - "6ea4a07e" # "evaluation/6ea4a07e.json",
  - "44f52bb0" # "training/44f52bb0.json",
  - "d5d6de2d" # "training/d5d6de2d.json",
  - "9110e3c5" # "evaluation/9110e3c5.json",
  - "27a28665" # "training/27a28665.json"