# Taken from https://github.com/volotat/ARC-Game/blob/main/tasks/levels.json
# There's no criteria for these splits, so these are subjective. https://github.com/volotat/ARC-Game/issues/7


task_ids:
  - "92e50de0" # "evaluation/92e50de0.json",
  - "e760a62e" # "evaluation/e760a62e.json",
  - "fe9372f3" # "evaluation/fe9372f3.json",
  - "ca8f78db" # "evaluation/ca8f78db.json",
  - "070dd51e" # "evaluation/070dd51e.json",
  - "16b78196" # "evaluation/16b78196.json",
  - "aa4ec2a5" # "evaluation/aa4ec2a5.json",
  - "aab50785" # "evaluation/aab50785.json",
  - "3ed85e70" # "evaluation/3ed85e70.json",
  - "fd096ab6" # "evaluation/fd096ab6.json",
  - "1a6449f1" # "evaluation/1a6449f1.json",
  - "a04b2602" # "evaluation/a04b2602.json",
  - "8719f442" # "evaluation/8719f442.json",
  - "5833af48" # "evaluation/5833af48.json",
  - "b457fec5" # "evaluation/b457fec5.json",
  - "fd4b2b02" # "evaluation/fd4b2b02.json",
  - "ea959feb" # "evaluation/ea959feb.json",
  - "5a5a2103" # "evaluation/5a5a2103.json",
  - "4aab4007" # "evaluation/4aab4007.json",
  - "1d0a4b61" # "evaluation/1d0a4b61.json",
  - "ccd554ac" # "evaluation/ccd554ac.json",
  - "58e15b12" # "evaluation/58e15b12.json",
  - "25094a63" # "evaluation/25094a63.json",
  - "903d1b4a" # "evaluation/903d1b4a.json",
  - "5b526a93" # "evaluation/5b526a93.json",
  - "e681b708" # "evaluation/e681b708.json",
  - "33b52de3" # "evaluation/33b52de3.json",
  - "de493100" # "evaluation/de493100.json",
  - "ac0c5833" # "evaluation/ac0c5833.json",
  - "93c31fbe" # "evaluation/93c31fbe.json",
  - "c97c0139" # "evaluation/c97c0139.json",
  - "09c534e7" # "evaluation/09c534e7.json",
  - "05a7bcf2" # "evaluation/05a7bcf2.json",
  - "b4a43f3b" # "evaluation/b4a43f3b.json",
  - "0934a4d8" # "evaluation/0934a4d8.json",
  - "40f6cd08" # "evaluation/40f6cd08.json",
  - "2753e76c" # "evaluation/2753e76c.json",
  - "9b2a60aa" # "evaluation/9b2a60aa.json",
  - "891232d6" # "evaluation/891232d6.json",
  - "762cd429" # "evaluation/762cd429.json",
  - "f9d67f8b" # "evaluation/f9d67f8b.json",
  - "b7f8a4d8" # "evaluation/b7f8a4d8.json",
  - "256b0a75" # "evaluation/256b0a75.json",
  - "d304284e" # "evaluation/d304284e.json",
  - "47996f11" # "evaluation/47996f11.json",
  - "96a8c0cd" # "evaluation/96a8c0cd.json",
  - "e41c6fd3" # "evaluation/e41c6fd3.json",
  - "833dafe3" # "evaluation/833dafe3.json",
  - "bcb3040b" # "evaluation/bcb3040b.json",
  - "79fb03f4" # "evaluation/79fb03f4.json",
  - "929ab4e9" # "evaluation/929ab4e9.json",
  - "ad7e01d0" # "evaluation/ad7e01d0.json",
  - "cad67732" # "evaluation/cad67732.json",
  - "981571dc" # "evaluation/981571dc.json",
  - "95a58926" # "evaluation/95a58926.json",
  - "5b692c0f" # "evaluation/5b692c0f.json",
  - "c663677b" # "evaluation/c663677b.json",
  - "a3f84088" # "evaluation/a3f84088.json",
  - "319f2597" # "evaluation/319f2597.json",
  - "a59b95c0" # "evaluation/a59b95c0.json",
  - "3f23242b" # "evaluation/3f23242b.json",
  - "5b6cbef5" # "evaluation/5b6cbef5.json",
  - "1e97544e" # "evaluation/1e97544e.json",
  - "e1d2900e" # "evaluation/e1d2900e.json",
  - "ba9d41b8" # "evaluation/ba9d41b8.json",
  - "af22c60d" # "evaluation/af22c60d.json",
  - "da515329" # "evaluation/da515329.json",
  - "d931c21c" # "evaluation/d931c21c.json",
  - "52fd389e" # "evaluation/52fd389e.json",
  - "f3b10344" # "evaluation/f3b10344.json",
  - "a57f2f04" # "evaluation/a57f2f04.json",
  - "e619ca6e" # "evaluation/e619ca6e.json",
  - "e95e3d8e" # "evaluation/e95e3d8e.json"